version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - /db/dataPotgreSQL:/var/lib/postgresql/data
      - /db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smartify
    networks:
      - internal

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile 
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=smartify
      - DB_PORT=5432
    container_name: backend
    restart: always
    networks:
      - external
      - internal

#  frontend:
#    build: ./frontend
#    container_name: frontend
#    restart: always

#
#  ml:
#    build: ./ml
#    container_name: ml
#    restart: always

networks:
  internal:
    internal: true
  external: