version: '3.8'

services:
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - smartify_test_internal
      - external
  db:
    image: postgres:15
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smartify
    restart: always
    networks:
      - smartify_test_internal
      - external

  mongo:
    image: mongo:7.0
    ports:
      - "27019:27017"
    volumes:
      - mongo_data:/data/db
      - ./database:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=smartify
    restart: always
    networks:
      - smartify_test_internal
      - external
    

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile 
    ports:
      - "22026:8080"
    depends_on:
      - db
      - mongo
      - mailhog
    env_file:
    - .env.test
    container_name: backend
    restart: always
    networks:
      - external
      - smartify_test_internal

#  frontend:
#    build: ./frontend
#    container_name: frontend
#    restart: always

#
#  ml:
#    build: ./ml
#    container_name: ml
#    restart: always

networks:
  internal:
    name: smartify_test_internal
    internal: true
  external:

volumes:
  postgres_test_data:
  mongo_test_data: