version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always

  ml:
    build: ./ml
    container_name: ml
    restart: always
